# Generated by Django 4.2.4 on 2023-08-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(blank=True, max_length=50)),
                ('LAST_NAME', models.CharField(blank=True, max_length=50)),
                ('USERNAME', models.CharField(blank=True, max_length=50)),
                ('PASSWORD', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
