# Generated by Django 4.2.4 on 2023-08-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='FIRST_NAME',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='LAST_NAME',
            new_name='last_name',
        ),
    ]
