# Generated by Django 4.2.4 on 2023-08-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_rename_first_name_admin_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('USERNAME', models.CharField(blank=True, max_length=50)),
                ('PASSWORD', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
