# Generated by Django 4.2.4 on 2023-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0003_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ADDRESS',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='DEPARTMENT',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='File',
            field=models.ImageField(blank=True, max_length=50, upload_to=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='MOBILE',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
