# Generated by Django 4.2.4 on 2023-09-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0004_doctor_address_doctor_department_doctor_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(blank=True, default='onhold', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='File',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
