# Generated by Django 4.2.4 on 2023-09-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0005_doctor_status_alter_doctor_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('USERNAME', models.CharField(blank=True, max_length=50)),
                ('PASSWORD', models.CharField(blank=True, max_length=50)),
                ('DEPARTMENT', models.CharField(blank=True, max_length=50)),
                ('MOBILE', models.CharField(blank=True, max_length=50)),
                ('ADDRESS', models.CharField(blank=True, max_length=50)),
                ('Symptoms', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, default='onhold', max_length=50)),
            ],
        ),
    ]
