# Generated by Django 4.2.4 on 2023-09-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0006_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
