# Generated by Django 4.2.4 on 2023-09-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0007_rename_first_name_patient_firstname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patient',
            new_name='patient_tb',
        ),
    ]
