# Generated by Django 4.2.4 on 2023-09-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0009_patient_tb_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, max_length=50)),
                ('Doctor_Department', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, default='onhold', max_length=50)),
            ],
        ),
    ]
