# Generated by Django 4.2.4 on 2023-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0012_rename_department_patient_tb_doctor_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='Date',
            field=models.DateField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
