# Generated by Django 4.2.4 on 2023-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0014_alter_book_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='ADDRESS',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='MOBILE',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
