# Generated by Django 4.2.4 on 2023-09-20 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0015_book_appointment_address_book_appointment_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='discharge_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_username', models.CharField(blank=True, max_length=50)),
                ('Doctor_username', models.CharField(blank=True, max_length=50)),
                ('Release_date', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('Room_charge', models.IntegerField(default=0)),
                ('Doc_fee', models.IntegerField(default=0)),
                ('Medicine_cost', models.ImageField(default=0, upload_to='')),
                ('Other_charge', models.IntegerField(default=0)),
                ('Total_charge', models.IntegerField(default=0)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospapp.patient_tb')),
            ],
        ),
    ]
