# Generated by Django 4.2.4 on 2023-09-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0017_book_appointment_patient_id_discharge_tb_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='USERNAME',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
